language: android

sudo: false

android:
  components:
  - build-tools-27.0.1
  - android-27
  - extra-android-m2repository
  - extra-android-support

script:
  - ./gradlew clean
  - ./gradlew assembleRelease